/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 education.gltf 
Author: ArbitraryCanary (https://sketchfab.com/ArbitraryCanary)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/k-vrc-love-death-robots-1a89dbad3a894642958405728ba66d9d
Title: K-VRC | Love, Death + Robots
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/robot_education/education.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.BlackMetal} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.ButterflyBody} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.ButterflyWings} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Glow} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.OrangePaint} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Screen} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Stripes} />
      </group>
    </group>
  )
}

useGLTF.preload('/education.gltf')
